//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GW2AddonManager.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StaticText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GW2AddonManager.Localization.StaticText", typeof(StaticText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addons.
        /// </summary>
        public static string AddOns {
            get {
                return ResourceManager.GetString("AddOns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体中文.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Companion Applications.
        /// </summary>
        public static string CompanionApplicationsWithLeadingSpace {
            get {
                return ResourceManager.GetString("CompanionApplicationsWithLeadingSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Shortcut.
        /// </summary>
        public static string CreateShortcut {
            get {
                return ResourceManager.GetString("CreateShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a shortcut to the application to the start menu - if program is moved, the shortcut will not function!.
        /// </summary>
        public static string CreateShortcutDescription {
            get {
                return ResourceManager.GetString("CreateShortcutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete all selected addons and all data associated with them! Are you sure you wish to continue?.
        /// </summary>
        public static string DeleteAddonsPrompt {
            get {
                return ResourceManager.GetString("DeleteAddonsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes the selected addons and all associated data.
        /// </summary>
        public static string DeleteDescription {
            get {
                return ResourceManager.GetString("DeleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Addons [!].
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developers: .
        /// </summary>
        public static string DevelopersColonSpace {
            get {
                return ResourceManager.GetString("DevelopersColonSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will disable the selected addons until you choose to re-enable them. Do you wish to continue?.
        /// </summary>
        public static string DisableAddonsPrompt {
            get {
                return ResourceManager.GetString("DisableAddonsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disables the selected addons.
        /// </summary>
        public static string DisableDescription {
            get {
                return ResourceManager.GetString("DisableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Addons.
        /// </summary>
        public static string DisableTitle {
            get {
                return ResourceManager.GetString("DisableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete.
        /// </summary>
        public static string DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will enable the selected addons. Do you wish to continue?.
        /// </summary>
        public static string EnableAddonsPrompt {
            get {
                return ResourceManager.GetString("EnableAddonsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Addons.
        /// </summary>
        public static string EnableTitle {
            get {
                return ResourceManager.GetString("EnableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Redownload.
        /// </summary>
        public static string ForceRedownload {
            get {
                return ResourceManager.GetString("ForceRedownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redownloads the addon loader and all addons regardless of version..
        /// </summary>
        public static string ForceRedownloadDescription {
            get {
                return ResourceManager.GetString("ForceRedownloadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game path.
        /// </summary>
        public static string GamePath {
            get {
                return ResourceManager.GetString("GamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 한국인.
        /// </summary>
        public static string Korean {
            get {
                return ResourceManager.GetString("Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Selected.
        /// </summary>
        public static string ManageSelected {
            get {
                return ResourceManager.GetString("ManageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot proceed, no game path has been set!.
        /// </summary>
        public static string NoGamePath {
            get {
                return ResourceManager.GetString("NoGamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs for GW2 not managed by the Addon Manager.
        /// </summary>
        public static string ProgramsNotManagedByThisApplication {
            get {
                return ResourceManager.GetString("ProgramsNotManagedByThisApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Enable.
        /// </summary>
        public static string ReEnable {
            get {
                return ResourceManager.GetString("ReEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the selected addons if they are disabled.
        /// </summary>
        public static string ReEnableDescription {
            get {
                return ResourceManager.GetString("ReEnableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Clean Install.
        /// </summary>
        public static string ResetToCleanInstall {
            get {
                return ResourceManager.GetString("ResetToCleanInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes all addons and plugins from Guild Wars 2..
        /// </summary>
        public static string ResetToCleanInstallDescription {
            get {
                return ResourceManager.GetString("ResetToCleanInstallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All addons and data deleted. The manager will now close..
        /// </summary>
        public static string ResetToCleanInstallDone {
            get {
                return ResourceManager.GetString("ResetToCleanInstallDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will delete ALL ADDONS and ALL DATA related to them, as well as the Addon Manager&apos;s data. Are you sure you wish to continue?.
        /// </summary>
        public static string ResetToCleanInstallWarning {
            get {
                return ResourceManager.GetString("ResetToCleanInstallWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all addons that you would like to install or update..
        /// </summary>
        public static string SelectAllAddonsDescription {
            get {
                return ResourceManager.GetString("SelectAllAddonsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an add-on to see more information about it..
        /// </summary>
        public static string SelectAnAddonToSeeMoreInformationAboutIt {
            get {
                return ResourceManager.GetString("SelectAnAddonToSeeMoreInformationAboutIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Directory.
        /// </summary>
        public static string SelectDirectory {
            get {
                return ResourceManager.GetString("SelectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage the game at the location in the text box.
        /// </summary>
        public static string SelectDirectoryDescription {
            get {
                return ResourceManager.GetString("SelectDirectoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You!.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using the GW2 Unofficial Addon Manager!.
        /// </summary>
        public static string ThankYouDescription {
            get {
                return ResourceManager.GetString("ThankYouDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE.
        /// </summary>
        public static string UpdateAllUpperCase {
            get {
                return ResourceManager.GetString("UpdateAllUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will download the application update and then restart the program..
        /// </summary>
        public static string UpdateDescription {
            get {
                return ResourceManager.GetString("UpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View this project on Github:.
        /// </summary>
        public static string ViewOnGithub {
            get {
                return ResourceManager.GetString("ViewOnGithub", resourceCulture);
            }
        }
    }
}
